name: sd

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    environment:
      - OTEL_COLLECTOR_EXPORTER_PROMETHEUS_ENDPOINT=${OTEL_COLLECTOR_EXPORTER_PROMETHEUS_ENDPOINT}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - JAEGER_COLLECTOR_URL=${JAEGER_COLLECTOR_URL}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - MIMIR_URL=${MIMIR_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    ports:
      - ${OTEL_COLLECTOR_RECEIVER_GRPC_PORT}:4317
      - ${OTEL_COLLECTOR_RECEIVER_HTTP_PORT}:4318
      - ${OTEL_COLLECTOR_EXPORTER_PROMETHEUS_PORT}:8889
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - sd-network

  discovery:
    image: alexengrig/discovery-service:${SERVICE_TAG}
    environment:
      - OTEL_SERVICE_NAME=discovery-service
    env_file:
      - otel.env
    ports:
      - ${DISCOVERY_PORT}:8761
    networks:
      - sd-network
    depends_on:
      - otel-collector

  producer:
    image: alexengrig/producer-service:${SERVICE_TAG}
    environment:
      - DISCOVERY_URL=${DISCOVERY_URL}
      - OTEL_SERVICE_NAME=producer-service
    env_file:
      - otel.env
    ports:
      - ${PRODUCER_PORT}:8082
    networks:
      - sd-network
    depends_on:
      - otel-collector
      - discovery

  consumer:
    image: alexengrig/consumer-service:${SERVICE_TAG}
    environment:
      - DISCOVERY_URL=${DISCOVERY_URL}
      - OTEL_SERVICE_NAME=consumer-service
    env_file:
      - otel.env
    ports:
      - ${CONSUMER_PORT}:8081
    networks:
      - sd-network
    depends_on:
      - otel-collector
      - discovery
      - producer

networks:
  sd-network:
    driver: bridge
