name: sd-grafana

services:
  prometheus:
    image: prom/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/prometheus.grafana.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    networks:
      - sd-network

  tempo:
    image: grafana/tempo
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}
    volumes:
      - tempo-data:/tmp/tempo
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml
    command:
      - -config.file=/etc/tempo/tempo.yml
    networks:
      - sd-network
    depends_on:
      - prometheus

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - ${MINIO_PORT}:9000
      - 45913:45913
    volumes:
      - minio-data:/data
    command: server /data
    networks:
      - sd-network

  mimir:
    image: grafana/mimir
    ports:
      - ${MIMIR_PORT}:9009
    volumes:
      - ./mimir/mimir.yml:/etc/mimir/mimir.yml
    command:
      - -config.file=/etc/mimir/mimir.yml
    networks:
      - sd-network
    depends_on:
      - minio

  grafana:
    image: grafana/grafana-enterprise
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - TEMPO_URL=${TEMPO_URL}
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - sd-network
    depends_on:
      - tempo
      #- mimir

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    environment:
      - TEMPO_OTLP_ENDPOINT=${TEMPO_OTLP_ENDPOINT}
      - MIMIR_URL=${MIMIR_URL}
    volumes:
      - ./otel-collector/config.grafana.yml:/etc/otelcol-contrib/config.yaml
    networks:
      - sd-network
    depends_on:
      - tempo
      #- mimir

volumes:
  tempo-data:
  minio-data:

networks:
  sd-network:
    driver: bridge
