name: sd

services:
  discovery:
    image: alexengrig/discovery-service:${SERVICE_TAG}
    environment:
      - OTEL_SERVICE_NAME=discovery-service
    env_file:
      - otel.env
    ports:
      - ${DISCOVERY_PORT}:8761
    networks:
      - sd-network

  producer:
    image: alexengrig/producer-service:${SERVICE_TAG}
    environment:
      - DISCOVERY_URL=${DISCOVERY_URL}
      - OTEL_SERVICE_NAME=producer-service
    env_file:
      - otel.env
    ports:
      - ${PRODUCER_PORT}:8082
    networks:
      - sd-network
    depends_on:
      - discovery

  consumer:
    image: alexengrig/consumer-service:${SERVICE_TAG}
    environment:
      - DISCOVERY_URL=${DISCOVERY_URL}
      - OTEL_SERVICE_NAME=consumer-service
    env_file:
      - otel.env
    ports:
      - ${CONSUMER_PORT}:8081
    networks:
      - sd-network
    depends_on:
      - discovery
      - producer

networks:
  sd-network:
    driver: bridge
