name: sd

services:
  tempo:
    image: grafana/tempo
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}
    volumes:
      - tempo-data:/tmp/tempo
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml
    command:
      - -config.file=/etc/tempo/tempo.yml
    networks:
      - sd-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/prometheus.grafana.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    networks:
      - sd-network

  loki:
    image: grafana/loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - sd-network

  grafana:
    image: grafana/grafana-enterprise
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - TEMPO_URL=${TEMPO_URL}
      - LOKI_URL=${LOKI_URL}
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - sd-network
    depends_on:
      - tempo
      - prometheus
      - loki

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    environment:
      - TEMPO_OTLP_ENDPOINT=${TEMPO_OTLP_ENDPOINT}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
    volumes:
      - ./otel-collector/config.grafana.yml:/etc/otelcol-contrib/config.yaml
    networks:
      - sd-network
    depends_on:
      - tempo
      - prometheus
      - loki

volumes:
  tempo-data:

networks:
  sd-network:
    driver: bridge
