apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: ${TEMPO_URL}
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
