apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: ${TEMPO_URL}
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
#      spanBar:
#        type: Tag
#        tag: otel.library.version
      lokiSearch:
        datasourceUid: loki
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: ['job', 'instance', 'pod', 'namespace']
        filterByTraceID: true
        filterBySpanID: true
        customQuery: true
        query: '{${__tags}}|="${__trace.traceid}"'
      serviceMap:
        datasourceUid: prometheus
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: ${LOKI_URL}
    jsonData:
      derivedFields:
        - name: Trace ID
          datasourceUid: tempo
          matcherRegex: '\"traceid\":\s*\"(\w+)\"'
          url: $${__value.raw}
          urlDisplayLabel: 'View Trace'
