receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: 'Trace ID'

      # the following attributes are added manually here in the example, but would
      # probably be added by other processors or straight from the source
#      - action: insert
#        key: spanid
#        from_context: 'Span ID'
#  resource:
#    attributes:
#      - action: insert
#        key: loki.resource.labels
#        value: host_name, pod_name
#
#      # the following attributes are added manually here in the example, but would
#      # probably be added by other processors or straight from the source
#      - action: insert
#        key: host_name
#        value: guarana
#      - action: insert
#        key: pod_name
#        value: guarana-pod-01

exporters:
  otlp/tempo:
    endpoint: ${TEMPO_OTLP_ENDPOINT}
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: ${PROMETHEUS_URL}/api/v1/write
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: ${LOKI_URL}/loki/api/v1/push
    tls:
      insecure: true
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/tempo
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheusremotewrite
    logs:
      receivers:
        - otlp
      processors:
        - batch
        - attributes
        #- resource
      exporters:
        - loki
        - logging
