receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  otlp/tempo:
    endpoint: ${TEMPO_OTLP_ENDPOINT}
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: ${PROMETHEUS_URL}/api/v1/write
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: ${LOKI_URL}/loki/api/v1/push
    tls:
      insecure: true
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/tempo
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheusremotewrite
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - loki
